/**
 * Code generator — AST to TypeScript source.
 *
 * Emits a single TypeScript file with a loadStory(engine: Engine) function
 * that mirrors the pattern in engine/src/demo-story.ts.
 */

import type {
  StoryFile,
  Declaration,
  KindDecl,
  ObjectDecl,
  RelationDecl,
  RuleNode,
  EveryTurnRuleNode,
  SceneNode,
  SceneHandlerNode,
  SceneCondition,
  NounPattern,
  Condition,
  Statement,
} from './ast.js';
import type { AnalysisResult } from './analyzer.js';
import { nameToId, escapeString, REVERSE_DIRECTIONS } from './utils.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generate(ast: StoryFile, analysis: AnalysisResult): string {
  const g = new CodeGenerator(ast, analysis);
  return g.generate();
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

class CodeGenerator {
  private lines: string[] = [];
  private indent = 0;

  constructor(
    private ast: StoryFile,
    private analysis: AnalysisResult,
  ) {}

  generate(): string {
    this.emitHeader();
    this.emitLine('');
    this.emitLine("import type { Engine } from '@chord/engine';");
    this.emitLine('');
    this.emitLine('export function loadStory(engine: Engine): void {');
    this.indent++;

    this.emitKinds();
    this.emitObjects();
    this.emitRelations();
    this.emitPropertyDefaults();
    this.emitPlayerStart();
    this.emitRules();
    this.emitEveryTurnRules();
    this.emitScenes();

    this.indent--;
    this.emitLine('}');
    this.emitLine('');

    return this.lines.join('\n');
  }

  // -----------------------------------------------------------------------
  // Header
  // -----------------------------------------------------------------------

  private emitHeader(): void {
    this.emitLine('/**');
    if (this.ast.title) {
      this.emitLine(` * ${this.ast.title}`);
    }
    if (this.ast.author) {
      this.emitLine(` * by ${this.ast.author}`);
    }
    this.emitLine(' *');
    this.emitLine(' * Generated by @chord/compiler. Do not edit by hand.');
    this.emitLine(' */');
  }

  // -----------------------------------------------------------------------
  // Kinds
  // -----------------------------------------------------------------------

  private emitKinds(): void {
    const kindDecls = this.ast.declarations.filter(
      (d): d is KindDecl => d.type === 'kind_decl',
    );
    if (kindDecls.length === 0) return;

    this.emitLine('');
    this.emitComment('Kinds');
    for (const k of kindDecls) {
      this.emitLine(`engine.addKind('${esc(k.name.toLowerCase())}', '${esc(k.parent.toLowerCase())}');`);
    }
  }

  // -----------------------------------------------------------------------
  // Objects
  // -----------------------------------------------------------------------

  private emitObjects(): void {
    const objectDecls = this.ast.declarations.filter(
      (d): d is ObjectDecl => d.type === 'object_decl',
    );
    if (objectDecls.length === 0) return;

    // Group by kind: rooms first, then others
    const rooms = objectDecls.filter(o => o.kind.toLowerCase() === 'room');
    const others = objectDecls.filter(o => o.kind.toLowerCase() !== 'room');

    if (rooms.length > 0) {
      this.emitLine('');
      this.emitComment('Rooms');
      for (const obj of rooms) {
        this.emitObjectDecl(obj);
      }
    }

    if (others.length > 0) {
      this.emitLine('');
      this.emitComment('Objects');
      for (const obj of others) {
        this.emitObjectDecl(obj);
      }
    }
  }

  private emitObjectDecl(obj: ObjectDecl): void {
    const id = nameToId(obj.name);
    const kind = obj.kind.toLowerCase();
    const loc = obj.location ? `'${esc(nameToId(obj.location))}'` : 'undefined';
    const desc = obj.description
      ? `'${esc(obj.description)}'`
      : "''";

    this.emitLine(`engine.addObject('${esc(id)}', '${esc(kind)}', ${loc}, ${desc});`);

    // Set default properties based on kind defaults
    const defaults = this.analysis.symbols.defaults.get(kind);
    if (defaults) {
      for (const [propName, def] of defaults) {
        const val = def.negated ? 'false' : 'true';
        this.emitLine(`engine.setProperty('${esc(id)}', '${esc(propName)}', '${val}');`);
      }
    }

    // Containers default to closed
    if (kind === 'container') {
      this.emitLine(`engine.setProperty('${esc(id)}', 'open', 'false');`);
    }
  }

  // -----------------------------------------------------------------------
  // Relations (exits)
  // -----------------------------------------------------------------------

  private emitRelations(): void {
    const relations = this.ast.declarations.filter(
      (d): d is RelationDecl => d.type === 'relation_decl',
    );
    if (relations.length === 0) return;

    this.emitLine('');
    this.emitComment('Exits');
    for (const rel of relations) {
      const subjectId = nameToId(rel.subjectName);
      const objectId = nameToId(rel.objectName);
      const dir = rel.direction;
      const revDir = REVERSE_DIRECTIONS[dir];
      if (revDir) {
        this.emitLine(
          `engine.addBidirectionalExit('${esc(objectId)}', '${esc(dir)}', '${esc(subjectId)}', '${esc(revDir)}');`,
        );
      } else {
        this.emitLine(
          `engine.addExit('${esc(objectId)}', '${esc(dir)}', '${esc(subjectId)}');`,
        );
      }
    }
  }

  // -----------------------------------------------------------------------
  // Property defaults
  // -----------------------------------------------------------------------

  private emitPropertyDefaults(): void {
    // Already handled inline in emitObjectDecl for kind-level defaults.
    // Here we handle any object-specific property settings from DefaultDecl
    // that reference specific objects rather than kinds.
    // (Currently, defaults target kinds, so this is a no-op.)
  }

  // -----------------------------------------------------------------------
  // Player placement
  // -----------------------------------------------------------------------

  private emitPlayerStart(): void {
    if (!this.ast.playerStart) return;
    this.emitLine('');
    this.emitComment('Player placement');
    const roomId = nameToId(this.ast.playerStart);
    this.emitLine(`engine.placePlayer('${esc(roomId)}');`);
  }

  // -----------------------------------------------------------------------
  // Rules
  // -----------------------------------------------------------------------

  private emitRules(): void {
    if (this.ast.rules.length === 0) return;

    this.emitLine('');
    this.emitComment('Rules');

    for (const rule of this.ast.rules) {
      this.emitLine('');
      this.emitRule(rule);
    }
  }

  private emitRule(rule: RuleNode): void {
    const priority = this.analysis.rulePriorities.get(rule) ?? 100;
    const ruleName = this.buildRuleName(rule);

    this.emitLine(`engine.registerRule('${esc(rule.verb)}', {`);
    this.indent++;
    this.emitLine(`name: '${esc(ruleName)}',`);
    this.emitLine(`priority: ${priority},`);
    this.emitLine(`phase: '${rule.phase}',`);
    this.emitLine('');

    // condition
    this.emitLine('condition(db, action) {');
    this.indent++;
    this.emitNounCheck(rule.nounPattern);
    this.emitConditionChecks(rule.conditions);
    this.emitLine('return true;');
    this.indent--;
    this.emitLine('},');
    this.emitLine('');

    // body
    this.emitLine('body(db, action) {');
    this.indent++;
    this.emitStatements(rule.body, rule.phase);
    this.indent--;
    this.emitLine('},');

    this.indent--;
    this.emitLine('});');
  }

  private buildRuleName(rule: RuleNode): string {
    const parts = [rule.phase, rule.verb];
    if (rule.nounPattern.type === 'specific') {
      parts.push(nameToId(rule.nounPattern.name));
    }
    return parts.join('-');
  }

  private emitNounCheck(pattern: NounPattern): void {
    switch (pattern.type) {
      case 'specific': {
        const id = nameToId(pattern.name);
        this.emitLine(`if (action.noun !== '${esc(id)}') return false;`);
        break;
      }
      case 'any':
        this.emitLine('if (!action.noun) return false;');
        break;
      case 'none':
        break;
    }
  }

  private emitConditionChecks(conditions: Condition[]): void {
    for (const cond of conditions) {
      switch (cond.type) {
        case 'property_test': {
          const objExpr = this.resolveObjectExpr(cond.objectName);
          const propName = cond.value.toLowerCase();
          if (cond.negated) {
            this.emitLine(
              `if (db.getProperty(${objExpr}, '${esc(propName)}') === 'true') return false;`,
            );
          } else {
            this.emitLine(
              `if (db.getProperty(${objExpr}, '${esc(propName)}') !== 'true') return false;`,
            );
          }
          break;
        }
        case 'location_test': {
          const objExpr = this.resolveObjectExpr(cond.objectName);
          const containerId = nameToId(cond.containerName);
          this.emitLine(
            `if (db.getLocation(${objExpr}) !== '${esc(containerId)}') return false;`,
          );
          break;
        }
        case 'player_location_test': {
          const roomId = nameToId(cond.roomName);
          this.emitLine(
            `if (db.getLocation('player') !== '${esc(roomId)}') return false;`,
          );
          break;
        }
        case 'comparison':
          // Deferred: arithmetic comparisons
          break;
      }
    }
  }

  // -----------------------------------------------------------------------
  // Statements
  // -----------------------------------------------------------------------

  private emitStatements(stmts: Statement[], phase?: string): void {
    let hasSay = false;
    let hasStop = false;

    for (const stmt of stmts) {
      switch (stmt.type) {
        case 'say':
          hasSay = true;
          // Accumulate — we'll combine into the return
          break;
        case 'now':
          this.emitNowStatement(stmt);
          break;
        case 'move':
          this.emitLine(
            `db.moveTo(${this.resolveObjectExpr(stmt.objectName)}, '${esc(nameToId(stmt.destinationName))}');`,
          );
          break;
        case 'remove':
          this.emitLine(`db.removeFrom(${this.resolveObjectExpr(stmt.objectName)});`);
          break;
        case 'stop':
          hasStop = true;
          break;
      }
    }

    // Build the return statement.
    // "instead" and "check" phases default to 'stop' (block the action)
    // unless the body explicitly does not include stop.
    // This matches Inform 7 semantics: Instead rules block by default.
    const implicitStop = (phase === 'instead' || phase === 'check') && !hasStop;
    const shouldStop = hasStop || implicitStop;

    const sayStmts = stmts.filter((s): s is import('./ast.js').SayStatement => s.type === 'say');
    const outputText = sayStmts.map(s => s.text).join(' ');

    if (shouldStop) {
      if (outputText) {
        this.emitLine(`return { outcome: 'stop', output: '${esc(outputText)}' };`);
      } else {
        this.emitLine("return { outcome: 'stop' };");
      }
    } else if (outputText) {
      this.emitLine(`return { outcome: 'continue', output: '${esc(outputText)}' };`);
    } else {
      this.emitLine("return { outcome: 'continue' };");
    }
  }

  private emitNowStatement(stmt: import('./ast.js').NowStatement): void {
    const objExpr = this.resolveObjectExpr(stmt.objectName);
    if (stmt.propertyName === '__carried') {
      // "now X is carried by the player" → moveTo(X, 'player')
      this.emitLine(`db.moveTo(${objExpr}, 'player');`);
    } else {
      this.emitLine(
        `db.setProperty(${objExpr}, '${esc(stmt.propertyName)}', '${esc(stmt.value)}');`,
      );
    }
  }

  // -----------------------------------------------------------------------
  // Every-turn rules
  // -----------------------------------------------------------------------

  private emitEveryTurnRules(): void {
    if (this.ast.everyTurnRules.length === 0) return;

    this.emitLine('');
    this.emitComment('Every-turn rules');

    for (const rule of this.ast.everyTurnRules) {
      this.emitLine('');
      this.emitEveryTurnRule(rule);
    }
  }

  private emitEveryTurnRule(rule: EveryTurnRuleNode): void {
    const priority = this.analysis.everyTurnPriorities.get(rule) ?? 10;
    const name = `every-turn-${this.ast.everyTurnRules.indexOf(rule) + 1}`;

    this.emitLine('engine.registerEveryTurnRule({');
    this.indent++;
    this.emitLine(`name: '${esc(name)}',`);
    this.emitLine(`priority: ${priority},`);
    this.emitLine('');

    // condition
    this.emitLine('condition(db) {');
    this.indent++;
    this.emitConditionChecks(rule.conditions);
    this.emitLine('return true;');
    this.indent--;
    this.emitLine('},');
    this.emitLine('');

    // body
    this.emitLine('body() {');
    this.indent++;
    this.emitStatements(rule.body);
    this.indent--;
    this.emitLine('},');

    this.indent--;
    this.emitLine('});');
  }

  // -----------------------------------------------------------------------
  // Scenes
  // -----------------------------------------------------------------------

  private emitScenes(): void {
    if (this.ast.scenes.length === 0) return;

    this.emitLine('');
    this.emitComment('Scenes');

    for (const scene of this.ast.scenes) {
      this.emitLine('');
      this.emitScene(scene);
    }
  }

  private emitScene(scene: SceneNode): void {
    const name = nameToId(scene.name);
    const beginHandler = this.ast.sceneHandlers.find(
      h => h.sceneName.toLowerCase() === scene.name.toLowerCase() && h.event === 'begins',
    );
    const endHandler = this.ast.sceneHandlers.find(
      h => h.sceneName.toLowerCase() === scene.name.toLowerCase() && h.event === 'ends',
    );

    this.emitLine('engine.registerScene({');
    this.indent++;
    this.emitLine(`name: '${esc(name)}',`);
    this.emitLine('');

    // beginsWhen
    this.emitLine('beginsWhen(db) {');
    this.indent++;
    this.emitSceneCondition(scene.beginsWhen);
    this.indent--;
    this.emitLine('},');
    this.emitLine('');

    // endsWhen
    this.emitLine('endsWhen(db) {');
    this.indent++;
    this.emitSceneCondition(scene.endsWhen);
    this.indent--;
    this.emitLine('},');

    // onBegin handler
    if (beginHandler) {
      this.emitLine('');
      this.emitLine('onBegin() {');
      this.indent++;
      const sayStmts = beginHandler.body.filter(
        (s): s is import('./ast.js').SayStatement => s.type === 'say',
      );
      if (sayStmts.length > 0) {
        const text = sayStmts.map(s => s.text).join(' ');
        this.emitLine(`return '${esc(text)}';`);
      } else {
        this.emitLine('return undefined;');
      }
      this.indent--;
      this.emitLine('},');
    }

    // onEnd handler
    if (endHandler) {
      this.emitLine('');
      this.emitLine('onEnd() {');
      this.indent++;
      const sayStmts = endHandler.body.filter(
        (s): s is import('./ast.js').SayStatement => s.type === 'say',
      );
      if (sayStmts.length > 0) {
        const text = sayStmts.map(s => s.text).join(' ');
        this.emitLine(`return '${esc(text)}';`);
      } else {
        this.emitLine('return undefined;');
      }
      this.indent--;
      this.emitLine('},');
    }

    this.indent--;
    this.emitLine('});');
  }

  private emitSceneCondition(cond: SceneCondition): void {
    switch (cond.type) {
      case 'play_begins':
        this.emitLine('return true;');
        break;
      case 'always':
        this.emitLine('return true;');
        break;
      case 'property_test': {
        const objId = nameToId(cond.objectName);
        const propName = cond.propertyName.toLowerCase();
        if (cond.negated) {
          this.emitLine(
            `return db.getProperty('${esc(objId)}', '${esc(propName)}') !== 'true';`,
          );
        } else {
          this.emitLine(
            `return db.getProperty('${esc(objId)}', '${esc(propName)}') === 'true';`,
          );
        }
        break;
      }
      case 'player_location': {
        const roomId = nameToId(cond.roomName);
        this.emitLine(`return db.getLocation('player') === '${esc(roomId)}';`);
        break;
      }
    }
  }

  // -----------------------------------------------------------------------
  // Helpers
  // -----------------------------------------------------------------------

  /** Resolve an object name to a TypeScript expression. */
  private resolveObjectExpr(name: string): string {
    const lower = name.toLowerCase();
    if (lower === 'noun' || lower === 'the noun') return 'action.noun!';
    if (lower === 'second noun' || lower === 'the second noun') return 'action.second!';
    if (lower === 'player' || lower === 'the player') return "'player'";
    return `'${esc(nameToId(name))}'`;
  }

  private emitLine(line: string): void {
    if (line === '') {
      this.lines.push('');
    } else {
      this.lines.push('  '.repeat(this.indent) + line);
    }
  }

  private emitComment(text: string): void {
    this.emitLine(`// ${'─'.repeat(67)}`);
    this.emitLine(`// ${text}`);
    this.emitLine(`// ${'─'.repeat(67)}`);
  }
}

function esc(s: string): string {
  return escapeString(s);
}
